services:
  db:
    image: postgres:15
    container_name: innovatv1-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kitt123
      POSTGRES_DB: erp_innovat
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  fastapi:
    image: ghcr.io/preylin/innovatv1:fastapi
    container_name: innovatv1-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./api/alembic/versions:/app/alembic/versions

  frontend:
    image: ghcr.io/preylin/innovatv1:frontend
    container_name: innovatv1-frontend
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi

volumes:
  pgdata: