services:
  db:
    image: postgres:15
    container_name: innovatv1-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: erp_innovat
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - internal-net

  fastapi:
    image: ghcr.io/preylin/innovatv1:fastapi
    container_name: innovatv1-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000"
    restart: always
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./api/alembic/versions:/app/alembic/versions
    networks:
      - internal-net
      - proxy-network

  frontend:
    image: ghcr.io/preylin/innovatv1:frontend
    container_name: innovatv1-frontend
    ports:
      - "80"
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
    networks:
      - internal-net
      - proxy-network
      
networks:
  internal-net: # Aísla la DB de todo lo demás
  proxy-network:
    external: true

volumes:
  pgdata: