name: CI/CD Rootless Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/preylin   # Tu registro en GitHub
      PROJECT: innovatv1          # Nombre de tu proyecto
      VPS_USER: deploy            # Usuario en el servidor
      VPS_IP: 66.94.108.125       # IP de tu servidor

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io # Especificamos el dominio directamente
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build FastAPI image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT }}:fastapi ./api

      - name: Build Frontend image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT }}:frontend ./frontend

      - name: Push images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}:fastapi
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}:frontend

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/docker/innovatv1
            docker pull ${{ env.REGISTRY }}/${{ env.PROJECT }}:fastapi
            docker pull ${{ env.REGISTRY }}/${{ env.PROJECT }}:frontend
            docker compose up -d