services:
  db:
    image: postgres:15
    container_name: innovatv1-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: erp_innovat
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - internal-net

  # --- NUEVO SERVICIO: REDIS ---
  redis:
    image: redis:7-alpine
    container_name: innovatv1-redis
    restart: always
    networks:
      - internal-net
    # No exponemos puertos a proxy-network porque solo la API hablará con él

  fastapi:
    image: ghcr.io/preylin/innovatv1:fastapi
    container_name: innovatv1-api
    # Agregamos parámetros para mejorar el manejo de WebSockets
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --forwarded-allow-ips="*"
    expose:
      - "8000"
    restart: always
    env_file: .env
    depends_on:
      - db
      - redis # Ahora depende de Redis también
    volumes:
      - ./api/alembic/versions:/app/alembic/versions
    networks:
      - internal-net
      - proxy-network

  frontend:
    image: ghcr.io/preylin/innovatv1:frontend
    container_name: innovatv1-frontend
    expose:
      - "80"
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
    networks:
      - internal-net
      - proxy-network

networks:
  internal-net:
    driver: bridge
  proxy-network:
    external: true

volumes:
  pgdata: