name: CI/CD Rootless Docker

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/preylin
      PROJECT: innovatv1
      VPS_USER: deploy
      VPS_IP: 66.94.108.125

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Create env file for Frontend
        run: |
          echo "VITE_API_BASE_URL=https://innovatv1.kittnight.com/api" > ./frontend/.env

      - name: Build FastAPI image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT }}:fastapi ./api

      - name: Build Frontend image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT }}:frontend ./frontend

      - name: Push images
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}:fastapi
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT }}:frontend

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "docker-compose.yml,nginx.conf,api/alembic/versions/*"
          target: "~/docker/innovatv1"
          strip_components: 0
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.VPS_IP }}
          username: ${{ env.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/docker/innovatv1
            
            # 1. Login en el VPS para evitar errores de Pull
            echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USER }} --password-stdin
            
            # 2. Pull de las nuevas im치genes
            docker compose pull
            
            # 3. Levantar servicios (Esto crear치 el contenedor de Redis autom치ticamente)
            docker compose up -d --remove-orphans
            
            # 4. Migraciones de Base de Datos
            # Usamos exec -T para que funcione en entornos sin terminal (CI)
            docker compose exec -T fastapi alembic upgrade head
            
            # 5. Limpieza de im치genes antiguas
            docker image prune -f